### PR TITLE
shared_mutex: return typed exceptional future in with_* error handlers

### LINKED ISSUE #1295: with_shared / with_lock exception handling does not support functors that return a value
As reported by @cvybhu in https://github.com/scylladb/seastar/commit/c4516f564197da409c1e5a012bd24c35457a9a40#r90053952:
```
My code compiled failed and print like error: could not convert ‘seastar::current_exception_as_future() [with T void>’ to ‘future<bool>’. In which the future<bool> is the return value of my lambda.
It captures:
this, uint64_t, std::string, enum class state_flag: uint64_t, sstring. I have no idea why it matches this template and why current_exception_as_future() has a wrong template T.
```

### PR DESCRIPTION
**Pull request by bhalevy**
Currently, exceptions in templates for functions that may
throw on move are handled in a generic way using
current_exception_as_future().

But if the passed functor returns a value, we need
to use current_exception_as_future<value_type> instead
so the error-free and error case returned future type
will match.

This change fixes that and adds unit test reproducers.

Fixes https://github.com/scylladb/seastar/issues/1295

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

### CODE REVIEW

**Comment by bhalevy** [comment]
@cvybhu, can you please test the patch in your environment?

**Comment by YifangSun** [comment]
> @cvybhu, can you please test the patch in your environment?

You seemed @ another people, bro.

**Comment by YifangSun** [comment]
@bhalevy Problem Solved. Thanks!  
BTW, how can I make my lambda satisfy std::is_nothrow_move_constructible_v<>

**Comment by bhalevy** [comment]
> > @cvybhu, can you please test the patch in your environment?
> 
> You seemed @ another people, bro. It's me.

Oops, sorry about that!

> @bhalevy Problem Solved. Thanks!

awesome!

> BTW, how can I make my lambda satisfy std::is_nothrow_move_constructible_v<>

Typically, you want all the lambda's captures to be `std::is_nothrow_move_constructible_v<>` as well.

File: include/seastar/core/shared_mutex.hh [hunk 1]
```diff
@@ -193,7 +193,33 @@ with_shared(shared_mutex& sm, Func&& func) noexcept {
...
+        return current_exception_as_future<>();
+    }
+}
+
+template <typename Func>
+SEASTAR_CONCEPT(
+    requires (std::invocable<Func> && !std::is_nothrow_move_constructible_v<Func> && !std::same_as<futurize_t<std::invoke_result_t<Func>>, future<>>)
+    inline
+    futurize_t<std::invoke_result_t<Func>>
+)
```
Comment (avikivity) [inline include/seastar/core/shared_mutex.hh:205]: You can use `futurize<T>::current_exception_as_future()` to avoid the duplication.

Comment (bhalevy) [reply include/seastar/core/shared_mutex.hh:205]: sounds like a good idea, I'll take a stab at it

**Comment by bhalevy** [comment]
In v2 ([0981560](https://github.com/scylladb/seastar/commit/0981560e4a5869b2e980ba6651513c14638f6eef)):
- simplified by by implementing @avikivity [idea](https://github.com/scylladb/seastar/pull/1296#discussion_r1023779286) using `futurize<std::invoke_result_t<Func>>::current_exception_as_future()`
