### PR TITLE
tls_test: abort_accept() after getting server socket

### LINKED ISSUE #1532: tls_test: fatal error: in "test_abort_accept_after_handshake": std::system_error: Software caused connection abort
Seen locally with seastar version a90a467d:
```
bhalevy@lt seastar$ mode=dev; ninja -C build/$mode test_unit_tls_run
ninja: Entering directory `build/dev'
[3/4] cd /home/bhalevy/dev/seastar/build/dev &.../seastar/build/dev/tests/unit/tls_test -- -c 2
Running 33 test cases...
INFO  2023-03-06 09:05:41,715 seastar - Reactor backend: io_uring
WARN  2023-03-06 09:05:41,716 [shard 0] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
INFO  2023-03-06 09:05:41,716 [shard 0] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
INFO  2023-03-06 09:05:41,716 [shard 0] seastar - IO queue uses 0.75ms latency goal for device 0
INFO  2023-03-06 09:05:41,716 [shard 0] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
INFO  2023-03-06 09:05:41,716 [shard 0] seastar - Created io queue dev(0) capacities: 512:2000:2000 1024:3000:3000 2048:5000:5000 4096:9000:9000 8192:17000:17000 16384:33000:33000 32768:65000:65000 65536:129000:129000 131072:257000:257000
WARN  2023-03-06 09:05:41,786 [shard 1] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
random-seed=1102295729
Established connection
Killing server side
Got expected exception
unknown location(0): fatal error: in "test_abort_accept_after_handshake": std::system_error: Software caused connection abort
/home/bhalevy/dev/seastar/src/testing/seastar_test.cc(43): last checkpoint
```

and the test hangs at this point

### LINKED ISSUE #1632: tls_test fails with kernel from ubuntu 22.04
```
-- Found LibUring: /usr/lib/x86_64-linux-gnu/liburing.so (found suitable version "2.2", minimum required is "2.0") 
...
63/74 Test #63: Seastar.unit.tls ..............................***Failed   42.58 sec
[0/1] cd /home/circleci/project/build/release && /usr/bin/cmake -E env ASAN_OPTIONS=disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1 BOOST_TEST_CATCH_SYSTEM_ERRORS=no /home/circleci/project/build/release/tests/unit/tls_test -- -c 2
Running 33 test cases...
INFO  2023-04-26 08:24:58,369 seastar - Reactor backend: io_uring
INFO  2023-04-26 08:24:58,369 [shard 0] seastar - Perf-based stall detector creation failed (EACCESS), try setting /proc/sys/kernel/perf_event_paranoid to 1 or less to enable kernel backtraces: falling back to posix timer.
INFO  2023-04-26 08:24:58,370 [shard 0] seastar - Created fair group io-queue-0 for 2 queues, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000, per tick grab 6291456
INFO  2023-04-26 08:24:58,370 [shard 0] seastar - IO queue uses 0.75ms latency goal for device 0
INFO  2023-04-26 08:24:58,370 [shard 0] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
INFO  2023-04-26 08:24:58,370 [shard 0] seastar - Created io queue dev(0) capacities: 512:2000:2000 1024:3000:3000 2048:5000:5000 4096:9000:9000 8192:17000:17000 16384:33000:33000 32768:65000:65000 65536:129000:129000 131072:257000:257000
random-seed=807866625
Established connection
Killing server side
Got expected exception
unknown location(0): fatal error: in "test_abort_accept_after_handshake": std::system_error: Software caused connection abort
/home/circleci/project/src/testing/seastar_test.cc(43): last checkpoint
```

see https://app.circleci.com/pipelines/github/tchaikov/seastar/622/workflows/e59cb589-3e70-4581-ac90-fdda605e3fee

### PR DESCRIPTION
**Pull request by tchaikov**
before this change, we get the `accept_result` after calling `abort_accept()`, but there is chance that the event from the fd which is registered for accept event is not fired yet, and the fd is closed, so what we get is an errno of EINVAL because `shutdown(fd, SHUT_RD)` is called. so `sa.get0()` throws a `system_error` instead of the `accept_result`.

this does not happen if the backend is `linux-aio`. but it surfaces occasionally when the io_uring backend is used.

Fixes #1532
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
tested in #1631

File: tests/unit/tls_test.cc [hunk 1]
```diff
@@ -410,9 +410,8 @@ SEASTAR_TEST_CASE(test_abort_accept_after_handshake) {
         b.set_x509_trust_file(certfile("catest.pem"), tls::x509_crt_format::PEM).get();
 
         auto c = tls::connect(b.build_certificate_credentials(), addr).get0();
-        server.abort_accept(); // should not affect the socket we got.
-
         auto s = sa.get0();
+        server.abort_accept(); // should not affect the socket we got.
```
Comment (avikivity) [inline tests/unit/tls_test.cc:414]: I think this points to a bug in our io_uring integration. In real life server.abort_accept() is not synchronized with calls to accept(). abort is called when shutting down, and accept is called by some tcp server trying to service new connections.

Comment (tchaikov) [reply tests/unit/tls_test.cc:414]: agreed, it is not synchronized. but IMHO, neither is it guaranteed that the "accepted" event is always delivered if the listening fd accepts a connection and then gets closed right away. i *think* io_uring processes the events in batch.

anyway, will take a closer look to see how/if we can fix this in the io_uring backend.

**Comment by tchaikov** [comment]
v2:

- changing the Fixes tag so it points to #1532

**Review by elcallio — APPROVED** [review]

File: tests/unit/tls_test.cc (hunk 1 above)
Comment (avikivity) [reply tests/unit/tls_test.cc:414]: You're right that regardless of a bug in the io_uring implementation, this tls_test is buggy too.
