### PR TITLE
net, websocket: replace Crypto++ calls with GnuTLS

### LINKED ISSUE #680: Required `cryptopp` dependency for.... `md5`?
I'm seeing if we can put `scylla` into `clearlinux`. But while packaging `seastar` I see it has a hard dependency for `cryptopp`.

It seems that this dependency is absolutely unwanted because (1) it's yet another copy of crypto algorithms we need to vet, secure and keep patched, and (2) it's probably unoptimized. (3) it's only needed for `md5` - do I see that right? Why? /sadface.

Can you please make `cryptopp` optional and allow distributions to link alternative `md5` implementations? Any of the algorithms from `openssl`, `gnutls` is fine, there's even the Linux kernel one available.

In the current condition I don't see `cryptopp` ever making it into clearlinux, so, this would be a blocker for us.

### LINKED ISSUE #746: future_state_base::set_exception may be called in state::invalid from future_state_base::set_to_broken_promise
Seen consistently since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/477/testReport/sstable_generation_loading_test/TestSSTableGenerationAndLoading/remove_index_file_test on shutdown
scylladb/scylla@791acc7f3858e5541ee216034f4c7111818510c5
seastar version e708d1df3a176081c3c478cd8b2f9e05f220154b

From https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/478/artifact/logs-release.2/1588985569545_sstable_generation_loading_test.TestSSTableGenerationAndLoading.remove_index_file_test/node1.log
scylladb/scylla@7da949026da980caf1cee0d96cce1dc76e6e736c
```
INFO  2020-05-09 00:52:38,104 [shard 0] init - Shutting down database
scylla: ./seastar/include/seastar/core/future.hh:344: void seastar::future_state_base::set_exception(std::__exception_ptr::exception_ptr&&): Assertion `_u.st == state::future' failed.
Aborting on shard 1.
Backtrace:
  0x0000000002e06632
  0x0000000002dafc74
  0x0000000002daff75
  0x0000000002db0010
  0x00007f65228ccb1f
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/7da949026da980caf1cee0d96cce1dc76e6e736c/scylla//opt/scylladb/libreloc/libc.so.6+0x000000000003c624
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/7da949026da980caf1cee0d96cce1dc76e6e736c/scylla//opt/scylladb/libreloc/libc.so.6+0x00000000000258d8
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/7da949026da980caf1cee0d96cce1dc76e6e736c/scylla//opt/scylladb/libreloc/libc.so.6+0x00000000000257a8
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/7da949026da980caf1cee0d96cce1dc76e6e736c/scylla//opt/scylladb/libreloc/libc.so.6+0x0000000000034a65
  0x0000000002d62f15
  0x0000000000c95969
  0x0000000002dac1a0
  0x0000000002dac3af
  0x0000000002de11c5
  0x0000000002def8fc
  0x0000000002d7ea9d
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/7da949026da980caf1cee0d96cce1dc76e6e736c/scylla//opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
  /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/7da949026da980caf1cee0d96cce1dc76e6e736c/scylla//opt/scylladb/libreloc/libc.so.6+0x00000000001016a2
```

```
(gdb) bt
#0  0x00007f6521e8b625 in raise () from /data/remove_index_file_test/libreloc/libc.so.6
#1  0x00007f6521e749ae in abort () from /data/remove_index_file_test/libreloc/libc.so.6
#2  0x00007f6521e747a9 in __assert_fail_base.cold () from /data/remove_index_file_test/libreloc/libc.so.6
#3  0x00007f6521e83a66 in __assert_fail () from /data/remove_index_file_test/libreloc/libc.so.6
#4  0x0000000002d62f16 in set_exception (ex=<optimized out>, this=<optimized out>) at ./seastar/include/seastar/core/future.hh:129
#5  seastar::future_state_base::set_to_broken_promise (this=this@entry=0x7f651f9e6b08) at ./seastar/src/core/future.cc:116
#6  0x0000000000c9596a in schedule<seastar::internal::promise_base_with_type<>, seastar::future<T>::then_wrapped_nrvo(Func&&) [with FuncResult = void; Func = seastar::smp_message_queue::async_work_item<Func>::run_and_dispose() [with Func = seastar::sharded<T>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<>(Service&)>) [with Service = database]::<lambda(unsigned int)>::<lambda()>]::<lambda(auto:49)>; T = {}]::<lambda()>::<lambda(pr_type&, seastar::future_state<>&&)> > (func=<optimized out>, 
    pr=<unknown type in /data/remove_index_file_test/libexec/scylla, CU 0x0, DIE 0x6e9f57>, this=0x7f651f9e6b00) at ./seastar/include/seastar/core/future.hh:336
#7  operator() (this=<optimized out>) at ./seastar/include/seastar/core/future.hh:1341
#8  then_wrapped_nrvo<void, seastar::smp_message_queue::async_work_item<Func>::run_and_dispose() [with Func = seastar::sharded<T>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<>(Service&)>) [with Service = database]::<lambda(unsigned int)>::<lambda()>]::<lambda(auto:49)> > (func=<optimized out>, this=0x7f651f9e6b00) at ./seastar/include/seastar/core/future.hh:1350
#9  then_wrapped_common<true, void, seastar::smp_message_queue::async_work_item<Func>::run_and_dispose() [with Func = seastar::sharded<T>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<>(Service&)>) [with Service = database]::<lambda(unsigned int)>::<lambda()>]::<lambda(auto:49)> > (func=<optimized out>, this=0x7f651f9e6b00) at ./seastar/include/seastar/core/future.hh:1370
#10 then_wrapped_maybe_erase<true, void, seastar::smp_message_queue::async_work_item<Func>::run_and_dispose() [with Func = seastar::sharded<T>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<>(Service&)>) [with Service = database]::<lambda(unsigned int)>::<lambda()>]::<lambda(auto:49)> > (func=<optimized out>, this=0x7f651f9e6b00) at ./seastar/include/seastar/core/future.hh:1319
#11 then_wrapped<seastar::smp_message_queue::async_work_item<Func>::run_and_dispose() [with Func = seastar::sharded<T>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<>(Service&)>) [with Service = database]::<lambda(unsigned int)>::<lambda()>]::<lambda(auto:49)> > (func=<optimized out>, this=0x7f651f9e6b00) at ./seastar/include/seastar/core/future.hh:1310
#12 seastar::smp_message_queue::async_work_item<seastar::sharded<database>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<> (database&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose() (this=0x600003b42930)
    at ./seastar/include/seastar/core/smp.hh:215
#13 0x0000000002dac1a1 in seastar::reactor::run_tasks (this=this@entry=0x601000066000, tq=...) at ./seastar/src/core/reactor.cc:2151
#14 0x0000000002dac3b0 in seastar::reactor::run_some_tasks (this=this@entry=0x601000066000) at ./seastar/src/core/reactor.cc:2566
#15 0x0000000002de11c6 in run_some_tasks (this=0x601000066000) at ./seastar/src/core/reactor.cc:2721
#16 seastar::reactor::run (this=0x601000066000) at ./seastar/src/core/reactor.cc:2721
#17 0x0000000002def8fd in seastar::smp::<lambda()>::operator()(void) const (__closure=<optimized out>) at ./seastar/include/seastar/core/reactor.hh:736
#18 0x0000000002d7ea9e in operator() (this=<optimized out>) at /usr/include/c++/9/bits/std_function.h:683
#19 seastar::posix_thread::start_routine (arg=<optimized out>) at ./seastar/src/core/posix.cc:60
#20 0x00007f65228c14e2 in start_thread () from /data/remove_index_file_test/libreloc/libpthread.so.0
#21 0x00007f6521f506a3 in clone () from /data/remove_index_file_test/libreloc/libc.so.6

#12 seastar::smp_message_queue::async_work_item<seastar::sharded<database>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<> (database&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose() (this=0x600003b42930)
    at ./seastar/include/seastar/core/smp.hh:215
215	            (void)futurator::invoke(this->_func).then_wrapped([this] (auto f) {
(gdb) ptype this
type = struct seastar::smp_message_queue::async_work_item<seastar::sharded<T>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<>(Service&)>) [with Service = database]::<lambda(unsigned int)>::<lambda()> > 
    [with Func = seastar::sharded<database>::<lambda(unsigned int)>::<lambda()>] : public seastar::smp_message_queue::work_item {
    seastar::smp_message_queue &_queue;
    Func _func;
    seastar::compat::optional _result;
    std::__exception_ptr::exception_ptr _ex;
    seastar::futurize<seastar::future<> >::promise_type _promise;
  public:
    async_work_item(seastar::smp_message_queue &, seastar::smp_service_group, <unknown type in /data/remove_index_file_test/libexec/scylla, CU 0x0, DIE 0x3c7743>);
    virtual void fail_with(std::__exception_ptr::exception_ptr);
    virtual void run_and_dispose(void);
    virtual void complete(void);
    future_type get_future(void);

    typedef seastar::futurize<seastar::future<> >::type future_type;
} * const

(gdb) down
#11 then_wrapped<seastar::smp_message_queue::async_work_item<Func>::run_and_dispose() [with Func = seastar::sharded<T>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<>(Service&)>) [with Service = database]::<lambda(unsigned int)>::<lambda()>]::<lambda(auto:49)> > (func=<optimized out>, this=0x7f651f9e6b00) at ./seastar/include/seastar/core/future.hh:1310
1310	        return then_wrapped_maybe_erase<true, FuncResult>(std::forward<Func>(func));
(gdb) p *this
$7 = {<seastar::internal::future_base> = {_promise = 0x0}, <seastar::internal::warn_variadic_future<false>> = {<No data fields>}, _state = {<seastar::future_state_base> = {_u = {st = seastar::future_state_base::invalid, ex = {
          _M_exception_object = 0x0}}}, <seastar::internal::uninitialized_wrapper<std::tuple<> >> = {<seastar::internal::uninitialized_wrapper_base<std::tuple<>, true>> = {<std::tuple<>> = {<No data fields>}, <No data fields>}, <No data fields>}, static copy_noexcept = true, 
    static has_trivial_move_and_destroy = true}, static copy_noexcept = <error reading variable: No global symbol "seastar::future<>::copy_noexcept".>}

#5  seastar::future_state_base::set_to_broken_promise (this=this@entry=0x7f651f9e6b08) at ./seastar/src/core/future.cc:116
116	        set_exception(std::make_exception_ptr(broken_promise{}));
(gdb) p *this
$8 = {_u = {st = seastar::future_state_base::invalid, ex = {_M_exception_object = 0x0}}}
```

Although this could be a bug in scylla shutting down the database I'm not sure this assert should disallow setting an exception in this state.

Cc @espindola @xemul

### PR DESCRIPTION
**Pull request by tchaikov**
since we already depend on GnuTLS which provides the functions which we use Crypto++ for. so let's rewrite the Crypto++ function calls using the ones provided by GnuTLS for less dependencies.

Fixes #680
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>

### CODE REVIEW

File: include/seastar/net/tcp.hh [hunk 1]
```diff
@@ -2090,7 +2088,7 @@ tcp_seq tcp<InetTraits>::tcb::get_isn() {
     hash[1] = _foreign_ip.ip;
     hash[2] = (_local_port << 16) + _foreign_port;
     hash[3] = _isn_secret.key[15];
-    CryptoPP::Weak::MD5::Transform(hash, _isn_secret.key);
+    gnutls_hash_fast(GNUTLS_DIG_MD5, _isn_secret.key, sizeof(_isn_secret.key), &hash);
```
Comment (nyh) [inline include/seastar/net/tcp.hh:2091]: I'm not an expert in these functions, but a quick glance on the gnutls_hash_fast() suggests that the last parameter is where the output is stored. So what's point of setting it in advanced?
I see below you have another use of gnutls_hash_fast() which doesn't set the output array...

File: src/websocket/server.cc [hunk 2]
```diff
@@ -123,14 +117,23 @@ future<> connection::process() {
...
 static std::string sha1_base64(std::string_view source) {
-    // CryptoPP insists on freeing the pointers by itself...
-    // It's leaky, but `read_http_upgrade_request` is a one-shot operation
-    // per handshake, so the real risk is not particularly great.
-    CryptoPP::SHA1 sha1;
-    std::string hash;
-    CryptoPP::StringSource(reinterpret_cast<const CryptoPP::byte*>(source.data()), source.size(),
-            true, new CryptoPP::HashFilter(sha1, new CryptoPP::Base64Encoder(new CryptoPP::StringSink(hash), false)));
-    return hash;
+    unsigned char hash[20];
```
Comment (nyh) [inline src/websocket/server.cc:120]: Nitpick: does GNUTLS have a macro for SHA1 length that perhaps we can use instead of "20"?

**Review by nyh — APPROVED** [review]
Looks good to me but I'm not an expert in either Crypto++ or GnuTLS (and I even left you a question on something that looks wrong to me, but maybe I'm missing something on how these libraries work).
Maybe you can just say a few words how you tested the areas which you changed to see you didn't break anything. Are the modified areas already covered by existing tests? Did you try something manually?

File: include/seastar/net/tcp.hh (hunk 1 above)
Comment (tchaikov) [reply include/seastar/net/tcp.hh]: see https://www.rfc-editor.org/rfc/rfc6528#section-3, we are generating the Initial Sequence Number Generation (ISN for short here), the md5 hash serves as the part of the function of `F` in 

```
ISN = M + F(localip, localport, remoteip, remoteport, secretkey)
```

where "F() is a pseudorandom function (PRF) of the connection-id."

to be more specific,  we just use the first byte of the md5 digest for `F(localip, localport, remoteip, remoteport, secretkey)`, as it fulfill the needs of the `F()` described in the RFC. the confusion comes from the somewhat unusual use of hash -- before my change, we used it as both input parameter and output parameter, `CryptoPP::Weak::MD5::Transform()` calculate the hash incrementally, so all 512 bits of `_isn_secret.key` are used without copying. see https://cryptopp.com/docs/ref/md5_8cpp_source.html#l00043 .

but i failed to take this into consideration in my previous change. and that's wrong. so in the latest revision, a hash handle is used for calculating the hash in multiple passes. and i put the rationales in the commit message.

File: src/websocket/server.cc (hunk 2 above)
Comment (tchaikov) [reply src/websocket/server.cc:120]: no, it does not. i checked both GnuTLS and searched around for projects using this library. no luck. i put more details in the commit message as well.

File: include/seastar/net/tcp.hh [hunk 3]
```diff
@@ -2089,8 +2087,14 @@ tcp_seq tcp<InetTraits>::tcb::get_isn() {
     hash[0] = _local_ip.ip;
     hash[1] = _foreign_ip.ip;
     hash[2] = (_local_port << 16) + _foreign_port;
-    hash[3] = _isn_secret.key[15];
-    CryptoPP::Weak::MD5::Transform(hash, _isn_secret.key);
+    gnutls_hash_hd_t md5_hash_handle;
+    // GnuTLS digests do not init at all, so this should never fail.
+    gnutls_hash_init(&md5_hash_handle, GNUTLS_DIG_MD5);
+    gnutls_hash(md5_hash_handle, hash, 3 * sizeof(hash[0]));
+    gnutls_hash(md5_hash_handle, _isn_secret.key, sizeof(_isn_secret.key));
```
Comment (avikivity) [inline include/seastar/net/tcp.hh:2094]: Isn't this changing the algorithm slightly? In the old code, we hashed key[15] twice. Probably it doesn't matter. @asias

File: include/seastar/net/tcp.hh [hunk 4]
```diff
@@ -2089,8 +2087,14 @@ tcp_seq tcp<InetTraits>::tcb::get_isn() {
     hash[0] = _local_ip.ip;
     hash[1] = _foreign_ip.ip;
     hash[2] = (_local_port << 16) + _foreign_port;
-    hash[3] = _isn_secret.key[15];
-    CryptoPP::Weak::MD5::Transform(hash, _isn_secret.key);
+    gnutls_hash_hd_t md5_hash_handle;
+    // GnuTLS digests do not init at all, so this should never fail.
+    gnutls_hash_init(&md5_hash_handle, GNUTLS_DIG_MD5);
```
Comment (avikivity) [inline include/seastar/net/tcp.hh:2092]: What about the memory allocation you mentioned?

**Comment by avikivity** [comment]
Looks good but information about testing would be good.

File: include/seastar/net/tcp.hh (hunk 4 above)
Comment (tchaikov) [reply include/seastar/net/tcp.hh:2092]: what you mean by "what about"? are you asking on the overhead incurred by the allocation/deallocation ?

File: include/seastar/net/tcp.hh (hunk 3 above)
Comment (tchaikov) [reply include/seastar/net/tcp.hh:2094]: agreed, this does change the existing algoritm. see https://cryptopp.com/docs/ref/md5_8cpp_source.html . i will update the commit message to reflect this change. but i don't think it matters.

**Comment by tchaikov** [comment]
i lost my virtualbox virtual machine which was setup for testing dpdk applications after messing up with my debian box,  not able to setup another at this moment. the testpmd application from dpdk works, but the httpd application from seastar fails even without my patch in this PR. probably something wrong with the NIC settings of the VM. will try harder later on.

**Comment by xemul** [comment]
@elcallio , please, take a look too

**Comment by bhalevy** [comment]
@tchaikov please rebase, and @elcallio please review after that

File: include/seastar/net/tcp.hh (hunk 4 above)
Comment (bhalevy) [reply include/seastar/net/tcp.hh:2092]: @avikivity ping

**Comment by bhalevy** [comment]
> Looks good but information about testing would be good.

@tchaikov please add this once retested.

**Review by elcallio — APPROVED** [review]

**Comment by nyh** [comment]
This is an old patch with many merge conflicts, Please rebase. Also, please say a few words on how you tested this. If I understood correctly (?) your patch affects only DPDK code, so you had to test it with DPDK but couldn't get it to work - if that's the case, I would say it's not enough testing...

File: src/websocket/server.cc (hunk 2 above)
Comment (avikivity) [reply src/websocket/server.cc:133]: I think the size of the hash is unlikely to ever change.

File: include/seastar/net/tcp.hh (hunk 3 above)
Comment (avikivity) [reply include/seastar/net/tcp.hh:2094]: @asias please ack

**Comment by tchaikov** [comment]
v2:

- rebased against master HEAD.

**Comment by tchaikov** [comment]
i just setup my machine for testing this change with following step:

```console
# # follow the instructions at https://core.dpdk.org/doc/quick-start/
# echo 64 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
$ ./configure.py --enable-dpdk --cook dpdk --compiler clang++ --c-compiler clang --mode release
$ ninja -C build/release/ httpd
$ build/release/apps/httpd/httpd --dpdk-pmd
INFO  2023-12-26 14:05:50,006 seastar - Reactor backend: io_uring
INFO  2023-12-26 14:05:50,009 seastar - Perf-based stall detector creation failed (EACCESS), try setting /proc/sys/kernel/perf_event_paranoid to 1 or less to enable kernel backtraces: falling back to posix timer.
starting prometheus API server
Seastar HTTP server listening on port 10000 ...
^CStoppping HTTP server
```

in another console on the same machine:
```
$ git describe 
3.0.1-49-ga211dd5
$ ./wrk -c 10 -d 10 -t 10 http://localhost:10000
```

== before this change
```console
$ ./wrk -c 10 -d 10 -t 10 http://localhost:10000
Running 10s test @ http://localhost:10000
  10 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    37.14us   82.80us   8.06ms   98.70%
    Req/Sec    29.75k     2.86k   37.07k    71.98%
  2989467 requests in 10.10s, 390.58MB read
Requests/sec: 295998.17
Transfer/sec:     38.67MB
```

== after this change
```console
$ ./wrk -c 10 -d 10 -t 10 http://localhost:10000                                                                                                                                                        14:11:09 [96/130]
Running 10s test @ http://localhost:10000
  10 threads and 10 connections                            
  Thread Stats   Avg      Stdev     Max   +/- Stdev                                                                    
    Latency    37.51us   84.38us   4.39ms   98.28%         
    Req/Sec    30.76k     3.26k   45.89k    73.98%
  3082189 requests in 10.10s, 402.70MB read                
Requests/sec: 305174.24                   
Transfer/sec:     39.87MB          
```

the change does not bring significant performance regression or break the functionality.

File: include/seastar/net/tcp.hh (hunk 4 above)
Comment (tchaikov) [reply include/seastar/net/tcp.hh:2094]: @avikivity i was trying to explain that `gnutls_has_init()` does not incur any performance regression which one might suspects that this could introduce due to the dynamic memory management. but i audited the code of GnuTLS when implementing this change and came to the conclusion.

**Comment by tchaikov** [comment]
@scylladb/seastar-maint hello maintainers, i rebased the change and tested it locally. could you please take a look? sorry for the latency.
