### PR TITLE
memory: Ensure thread locals etc are minimally initialized even with non-seastar reactor options for alloc

### LINKED ISSUE #2148: Running without `SEASTAR_USE_DEFAULT_ALLOCATOR` but smp_opts.memory_allocator != memory_allocator::seastar breaks
Found in https://github.com/scylladb/scylladb/issues/17880.

When using the seastar allocator, there are numerous implicit reliances on `cpu_mem_ptr` having been set up. Previously, this just happened to be true, due to #2137. With that fixed, suddenly it is not, unless `smp::configure` is invoked with `memory_allocator == memory_allocator::seastar`. 

It not being so is rare, and the test we have for it is only run for dpdk builds (why?). And even so, does not provoke the problem, since it normally never hits a reactor poller or similar. Adding a small sleep to the test fixes this -> crash.

### PR DESCRIPTION
**Pull request by elcallio**
Fixes #2148

When using the seastar allocator, there are numerous implicit reliances on cpu_mem_ptr having been set up. Previously, this just happened to be true, due to #2137.

Fixed by adding a minimal memory setup call to smp::configure, even if using non-seastar allocator reactor options (not compile flags).

Fixed the test for the feature (allocator options) so that it 
* Actually runs. regardlerss of dpdk
* Actually catches the issue

### CODE REVIEW

File: src/core/reactor.cc [hunk 1]
```diff
@@ -4414,6 +4414,12 @@ void smp::configure(const smp_options& smp_opts, const reactor_options& reactor_
     std::optional<memory::internal::numa_layout> layout;
     if (smp_opts.memory_allocator == memory_allocator::seastar) {
         layout = memory::configure(allocations[0].mem, mbind, use_transparent_hugepages, hugepages_path);
+    } else {
+        // #2148 - if running seastar allocator but options that contradict this, we still need to
+        // init memory at least minimally, otherwise a bunch of stuff breaks.
+        // Previously, we got away wth this by accident due to #2137.
+        // Calling memory::configure without any memory etc will fix up internal structures enough.
+        memory::configure({}, mbind, false, std::nullopt);
```
Comment (denesb) [inline src/core/reactor.cc:4422]: We should passe `false` as `mbind` as well. Our docs claim that `--mbind` is ignored when non-seastar allocator is used, so we should ignore it.

Comment (elcallio) [reply src/core/reactor.cc]: fair enough.

File: src/core/reactor.cc [hunk 2]
```diff
@@ -4414,6 +4414,12 @@ void smp::configure(const smp_options& smp_opts, const reactor_options& reactor_
     std::optional<memory::internal::numa_layout> layout;
     if (smp_opts.memory_allocator == memory_allocator::seastar) {
         layout = memory::configure(allocations[0].mem, mbind, use_transparent_hugepages, hugepages_path);
+    } else {
+        // #2148 - if running seastar allocator but options that contradict this, we still need to
+        // init memory at least minimally, otherwise a bunch of stuff breaks.
+        // Previously, we got away wth this by accident due to #2137.
+        // Calling memory::configure without any memory etc will fix up internal structures enough.
+        memory::configure({}, false, false, std::nullopt);
```
Comment (denesb) [inline src/core/reactor.cc:4422]: I just checked and this will set `is_reactor_thread=true`, which means that the seastar allocator will start serving allocation requests. This effectively breaks `smp_options::memory_allocator = memory_allocator::standard`, which scylla tools use.

Comment (elcallio) [reply src/core/reactor.cc:4422]: An alternative option is adding "config_minimal" that only does init_cpu_mem().

Comment (elcallio) [reply src/core/reactor.cc]: Changed to the above.

**Review by denesb — APPROVED** [review]

**Comment by avikivity** [comment]
Where do we rely on cpu_mem? Shouldn't they be guarded by is_reactor_thread?

**Comment by elcallio** [comment]
No. A bunch of calls, like `seastar::memory::get_memory_layout()` rely on cpu_mem being inited, and are called from scylla both before, and regardless of whether, reactor has been created. Or whether said reactor is created with, or without seastar allocation enabled. 
There are a bunch of assumptions and interdependencies in(scylla) tests as well, which test features that more or less implicitly depend on this without a reactor init. Not sure why those did not fail for me on the initial SIF fix (pretty sure I ran a full scylla test.py on it).

**Comment by elcallio** [comment]
As to "should", one could indeed wish...

File: tests/unit/app-template_test.cc [hunk 3]
```diff
@@ -53,7 +52,11 @@ BOOST_AUTO_TEST_CASE(app_standard_memory_allocator,
     int actual_status = app.run(
         std::size(args), std::data(args),
         [expected_status] {
-            return make_ready_future<int>(expected_status);
+            // #2148 - add a small sleep to ensure the reactor does
+            // some of its background stuff, pollers etc for example.
+            return seastar::sleep(2s).then([expected_status] {
+                return make_ready_future<int>(expected_status);
```
Comment (avikivity) [inline tests/unit/app-template_test.cc:58]: New flaky test!

File: src/core/memory.cc [hunk 4]
```diff
@@ -1641,6 +1641,13 @@ void *allocate_slowpath(size_t size) {
             return original_malloc_func(size);
         }
 
+        // original_malloc_func might be null for allocations before main
+        // in constructors before original_malloc_func ctor is called
+        // Note on #2137: Moved to here, because there is lots of code 
+        // that implicitly relies on the SIF below to have occurred, and thus
```
Comment (avikivity) [inline src/core/memory.cc:1647]: What is SIF?

Comment (tchaikov) [reply src/core/memory.cc:1647]: guess it's static init fiasco .

File: tests/unit/app-template_test.cc (hunk 3 above)
Comment (elcallio) [reply tests/unit/app-template_test.cc:58]: Should not be, as we will crash as soon as pollers are invoked. Considered waiting for something, but that is just the same thing. Need to ensure we simply end up in task queue, and a reactor poll is done.

File: src/core/memory.cc (hunk 4 above)
Comment (elcallio) [reply src/core/memory.cc:1647]: static init fiasco.

File: src/core/reactor.cc [hunk 5]
```diff
@@ -4584,7 +4596,16 @@ void smp::configure(const smp_options& smp_opts, const reactor_options& reactor_
     _qs_owner = decltype(smp::_qs_owner){new smp_message_queue* [smp::count], qs_deleter{}};
     _qs = _qs_owner.get();
     for(unsigned i = 0; i < smp::count; i++) {
-        smp::_qs_owner[i] = reinterpret_cast<smp_message_queue*>(operator new[] (sizeof(smp_message_queue) * smp::count));
+        smp::_qs_owner[i] = reinterpret_cast<smp_message_queue*>(operator new[] (sizeof(smp_message_queue) * smp::count
+        // smp_message_queue has members with hefty alignment requirements.
+        // if we are reactor thread, or not running with dpdk, doing this
+        // new default aligned seemingly works, as does reordering
+        // dlinit dependencies (ugh). But we should enforce calling out to
+        // aligned_alloc, instead of pure malloc, if possible.
```
Comment (tchaikov) [inline src/core/reactor.cc:4604]: i don't quite understand this part.. 

i am not questioning the correctness of this change. as `__STDCPP_DEFAULT_NEW_ALIGNMENT__` is 16. and `sizeof(smp_message_queue)` is greater than 16. so this change should enforce the alignment of the allocated storage.

but how is this related to if we are seastar reactor or using a dpdk reactor? do you mean, we could perform unaligned access when using dpdk?

File: tests/unit/app-template_test.cc [hunk 6]
```diff
@@ -24,22 +24,21 @@
...
-                     *boost::unit_test::enable_if<with_dpdk>()) {
+// #2148 - always run this.
+BOOST_AUTO_TEST_CASE(app_standard_memory_allocator) {
     // by default, use conservative settings instead of maxing out the performance
     // for testing app_template and underlying reactor's handling of different
     // settings
     app_template::seastar_options opts;
-    opts.smp_opts.thread_affinity.set_value(false);
+    // Here was a `opts.smp_opts.thread_affinity.set_value(false);`.
+    // This breaks the subsequent tests below (which run non-smp-1 config).
```
Comment (tchaikov) [inline tests/unit/app-template_test.cc:39]: i am not following you. yes, we do have non-smp-1 tests in this source file. but why does your change break them?

File: src/core/reactor.cc (hunk 5 above)
Comment (elcallio) [reply src/core/reactor.cc:4604]: When building with dpdk, we get a slightly different init sequence, which, when fixing the original SIF such that non-reactor allocation goes to libc malloc from the get-go, causes the above new/alloc to end up in different memory blocks -> without SIF fix we get nice, page-level memory. With it, we end up in normal malloc and get 16/8-aligned block. I can only assume because in the former case, we've done a bunch of library allocs actually via seastar allocator, which in turn means we've stolen a bunch of pages and thus impact where malloc, once called, will place things. 

Now, I assume that normally the allocation here should compensate for this unless calling a new(aligned) alloc, and over-alloc + adjust pointers + make the end result object messy internally (finding the original memory etc), but either due to the raw memory alloc + alloc in place, or something else I am missing, this does not happen. 

Honestly, I would love to have a more exact and detailed explanation, but my tolerance for single-instructioning myself through libc etc only goes so far. Should also be observed that the failure does not happen if running in gdb either, possibly because some slight .so loading difference there as well. 

In any case, what I could observe is alignment of memory we actually get in the two variants, and when if works we get properly aligned memory, even though the new goes to a simple malloc. Luck?

File: tests/unit/app-template_test.cc (hunk 3 above)
Comment (tchaikov) [reply tests/unit/app-template_test.cc:58]: i understand that pollers are also queued like other tasks. but why does it matter? what exactly are we waiting? what happens if we do not wait long enough? could you please elaborate it a little bit?

File: tests/unit/app-template_test.cc (hunk 6 above)
Comment (elcallio) [reply tests/unit/app-template_test.cc:39]: It does not. But running the tests with and without it does. Something gets confused with some thread-local somewhere, such that the latter tests cannot init, because smp::invoke_all fails to complete.

File: src/core/memory.cc (hunk 4 above)
Comment (tchaikov) [reply src/core/memory.cc:1647]: probably, would be better to repeat "static init fiasco" here, before "SIF" becomes a well-known abbreviation, like, for instance, OOM.

File: tests/unit/app-template_test.cc (hunk 6 above)
Comment (elcallio) [reply tests/unit/app-template_test.cc:39]: In fact, the service_group semaphores gets confused.

File: tests/unit/app-template_test.cc (hunk 3 above)
Comment (elcallio) [reply tests/unit/app-template_test.cc:58]: Pollers are run when we have nothing to run/after a task iteration. Even 2s here is probably on the high side. Just as long as we're pushed into the task queue, we should provoke the issue.

File: src/core/memory.cc (hunk 4 above)
Comment (elcallio) [reply src/core/memory.cc:1647]: Sure.

File: tests/unit/app-template_test.cc (hunk 6 above)
Comment (elcallio) [reply tests/unit/app-template_test.cc]: I changed my mind. Better to fix the issue.

File: src/core/reactor.cc (hunk 5 above)
Comment (avikivity) [reply src/core/reactor.cc:4604]: The seastar allocator has a power-of-two thing so it gets naturally aligned, and I guess libc does not, so it makes sense.

Comment (avikivity) [reply src/core/reactor.cc:4604]: And, the original code was just broken - it bypassed the new-expression to call operator new directly (maybe to avoid allocating the array size), but "forgot" to align properly.

Comment (elcallio) [reply src/core/reactor.cc:4604]: Note however that we could get past this (by luck?) even when running with such options that the new call was always served by glibc malloc. Otoh, even then, we'd mostly have smp_count > 1 (i.e. 8 or so), and thus at least fall into larger alloc domain.

File: tests/unit/app-template_test.cc (hunk 3 above)
Comment (elcallio) [reply tests/unit/app-template_test.cc:58]: I've updated the comment to be more explicit about what we try to do.

File: src/core/reactor.cc [hunk 7]
```diff
@@ -4584,7 +4596,16 @@ void smp::configure(const smp_options& smp_opts, const reactor_options& reactor_
...
+#ifdef __cpp_aligned_new
+            , std::align_val_t(alignof(smp_message_queue))
+#endif
+        ));
```
Comment (avikivity) [inline src/core/reactor.cc:4608]: __cpp_aligned_new is from 2018 (gcc and clang), we can avoid the #ifdef

Comment (elcallio) [reply src/core/reactor.cc:4608]: Just being consistent with the definition of the aligned alloc functions in memory.cc.

File: src/core/reactor.cc (hunk 5 above)
Comment (tchaikov) [reply src/core/reactor.cc:4604]: thank you very much Calle, all clear!

File: tests/unit/app-template_test.cc (hunk 6 above)
Comment (tchaikov) [reply tests/unit/app-template_test.cc]: thanks!

File: src/core/reactor.cc (hunk 7 above)
Comment (tchaikov) [reply src/core/reactor.cc:4608]: probably we can drop them all together in another change?

**Review by tchaikov — APPROVED** [review]
lgtm. thanks!

**Comment by tchaikov** [comment]
@avikivity @scylladb/seastar-maint hello maintainers, could you help review this change?

**Review by denesb — APPROVED** [review]

File: src/core/memory.cc (hunk 4 above)
Comment (nyh) [reply src/core/memory.cc]: Arguably, even the pharse "static init fiasco" doesn't mean anything to the uninitiated.

File: src/core/reactor.cc (hunk 7 above)
Comment (tchaikov) [reply src/core/reactor.cc:4608]: FWIW, Avi is removing them in #2150 .

Comment (elcallio) [reply src/core/reactor.cc:4603]: Ok, removed.
