### PR TITLE
shared_ptr_debug_helper: turn assert into on_internal_error_abort

### LINKED ISSUE #1095: on_internal_error_noexcept() may return, is that useful?
In commit 3c095cd66f8dbd33ef10abbc6ed425103fe7d96c, @denesb added a `on_internal_error_noexcept` function.

Whereas the regular `on_internal_error` is `[[noreturn]]` - it always crashes or throws - the "noexcept" variant is **not** `[[noreturn]]`. Depending on the setting of the abort_on_internal_error flag, it either crashes or... just returns.

It's not clear to me why would anyone want such a behavior, or how such a function can ever be used correctly. For example, in one Scylla commit https://github.com/scylladb/scylla/pull/10691/commits/93e8ffec1cb79cbf12b0818df843f33c7f95023e @bhalevy ended up using it in the following way:
```c++
               on_internal_error_noexcept(tlogger, format("Memtable flush failed due to: {}", e));
                // If the node is configured to not abort on internal error,
                // but propagate it up the chain, we can't do anything reasonable
                // at this point.
                abort();
```

Isn't this what all callers would want?

Or maybe there's some other use case of on_internal_error_noexcept that I'm not familiar with?

### PR DESCRIPTION
**Pull request by bhalevy**
Add `on_internal_error_abort` that prints the internal error log message and aborts unconditionally.

It allows the caller to log more information than what would have been printed just from the failed assert.

In addition, use it in the `shared_ptr_debug_helper` to replace the assert call, that is not useful in debug runs since the address sanitizer obfuscates the assert backtrace.

Fixes #1095

### CODE REVIEW

File: include/seastar/core/on_internal_error.hh [hunk 1]
```diff
@@ -54,4 +54,11 @@ bool set_abort_on_internal_error(bool do_abort) noexcept;
 /// in noexcept contexts like destructors or noexcept functions.
 void on_internal_error_noexcept(logger& logger, std::string_view reason) noexcept;
 
+/// Report an internal error and abort unconditionally
+///
+/// The error will be logged to \logger and the program will be aborted,
+/// regardless of the abort_on_internal_error setting.
+/// This overload can be used to replace assert().
+void on_internal_error_abort(logger& logger, std::string_view reason) noexcept;
```
Comment (denesb) [inline include/seastar/core/on_internal_error.hh:62]: Maybe `on_internal_fatal_error()` would be a better name.

Comment (bhalevy) [reply include/seastar/core/on_internal_error.hh:62]: on_fatal_internal_error sounds better IMO

Comment (denesb) [reply include/seastar/core/on_internal_error.hh:62]: fine by me

**Comment by bhalevy** [comment]
In v2 ([be0a4c6](https://github.com/scylladb/seastar/commit/be0a4c6811abf1d0dabd24e8b1fed5a9a93e3092)):
- renamed to on_fatal_internal_error
- don't fmt::format std::thread::id, just print plain text on shared_ptr_debug_helper fatal internal error.

**Review by denesb — APPROVED** [review]

**Comment by bhalevy** [comment]
CI failure https://app.circleci.com/pipelines/github/bhalevy/seastar/18/workflows/bc91682a-1bec-48fe-924b-a927c11b80cd/jobs/212
is #1190 (which I'm working on separately)

File: src/core/on_internal_error.cc [hunk 2]
```diff
@@ -58,3 +58,8 @@ void seastar::on_internal_error_noexcept(logger& logger, std::string_view msg) n
         abort();
     }
 }
+
+void seastar::on_fatal_internal_error(logger& logger, std::string_view msg) noexcept {
+    set_abort_on_internal_error(true);
+    on_internal_error_noexcept(logger, msg);
```
Comment (xemul) [inline src/core/on_internal_error.cc:64]: Why not just
```c++
    logger.error("{}, at: {}", msg, current_backtrace());
    abort();
```
?

Comment (bhalevy) [reply src/core/on_internal_error.cc:64]: can do, I just wanted to use the common code.
maybe we can refactor the logger.error part into a common function that both places can call.

File: include/seastar/core/shared_ptr_debug_helper.hh [hunk 3]
```diff
@@ -60,7 +65,9 @@ public:
     }
 private:
     void check() const {
-        assert(_cpu == std::this_thread::get_id());
+        if (__builtin_expect(_cpu != std::this_thread::get_id(), false)) {
```
Comment (nyh) [inline include/seastar/core/shared_ptr_debug_helper.hh:68]: I think C++20 `[[unlikely]]` is nicer, but this is also correct.

**Review by nyh — APPROVED** [review]
The patch itself looks good, but the sentence in the commit message said "we lose the assert backtrace in debug mode, with the address sanitizer" suggest that perhaps we'll find ourselves replacing all asserts with his new function, one by one, each time we discover that assert is missing a backtrace in debug code. Can't we fix assert. instead?

File: include/seastar/core/shared_ptr_debug_helper.hh (hunk 3 above)
Comment (bhalevy) [reply include/seastar/core/shared_ptr_debug_helper.hh:68]: agreed, but we still have to support c++17 in seastar

**Comment by bhalevy** [comment]
> Can't we fix assert. instead?

I think we should, as a followup, but our experience with scylla shows that people want this `on_fatal_internal_error` helper anyway as it allows to print additional information to what would be printed with a plain assert.
Maybe I need to add that the commit message as part of the motivation for the helper.

File: include/seastar/core/on_internal_error.hh [hunk 4]
```diff
@@ -54,4 +54,11 @@ bool set_abort_on_internal_error(bool do_abort) noexcept;
 /// in noexcept contexts like destructors or noexcept functions.
 void on_internal_error_noexcept(logger& logger, std::string_view reason) noexcept;
 
+/// Report an internal error and abort unconditionally
+///
+/// The error will be logged to \logger and the program will be aborted,
+/// regardless of the abort_on_internal_error setting.
+/// This overload can be used to replace assert().
+void on_fatal_internal_error(logger& logger, std::string_view reason) noexcept;
```
Comment (avikivity) [inline include/seastar/core/on_internal_error.hh:62]: It should be marked [[noreturn]] so the compiler knows can convert the assertion into an optimization hint.

File: src/core/on_internal_error.cc (hunk 2 above)
Comment (avikivity) [reply src/core/on_internal_error.cc:64]: It's common code but obfuscated.

File: include/seastar/core/shared_ptr_debug_helper.hh [hunk 5]
```diff
@@ -25,9 +25,14 @@
 
 #include <thread>
 #include <cassert>
+#include <fmt/format.h>
+
```
Comment (avikivity) [inline include/seastar/core/shared_ptr_debug_helper.hh:29]: Why is this include needed?

File: include/seastar/core/on_internal_error.hh (hunk 4 above)
Comment (bhalevy) [reply include/seastar/core/on_internal_error.hh:62]: right. will do

Comment (bhalevy) [reply include/seastar/core/on_internal_error.hh:62]: right. will do

File: include/seastar/core/shared_ptr_debug_helper.hh (hunk 5 above)
Comment (bhalevy) [reply include/seastar/core/shared_ptr_debug_helper.hh:29]: I'm not sure. Maybe the editor added it without me noticing

Comment (bhalevy) [reply include/seastar/core/shared_ptr_debug_helper.hh:29]: Now I remembered, my original patch printed the differing thread id:s but fmt complained they are not formattable, yet the include directive remained.

**Comment by bhalevy** [comment]
In v2 ([b6bd5f0](https://github.com/scylladb/seastar/commit/b6bd5f01ff7fc110645711bf245fc3813c7abe3d)):
- simplified `on_fatal_internal_error`
  - improved commit message
- on_internal_error: refactor log_error_and_backtrace
- removed extraneous include of fmt/format.hh from shared_ptr_debug_helper.hh

File: src/core/on_internal_error.cc [hunk 6]
```diff
@@ -33,9 +33,13 @@ bool seastar::set_abort_on_internal_error(bool do_abort) noexcept {
     return abort_on_internal_error.exchange(do_abort);
 }
 
+static void log_error_and_backtrace(logger& logger, std::string_view msg) {
```
Comment (xemul) [inline src/core/on_internal_error.cc:36]: nit: `noexcept`

Comment (bhalevy) [reply src/core/on_internal_error.cc]: added in v3
