### PR TITLE
json: formatter: fix formatting of std:string_view

### LINKED ISSUE #3183: std::string_view is wrongly formatter by to_json as array of integers rather than a json string
For example: std::string_view("hello, world") is wrongly formatted as [104,101,108,108,111,44,32,119,111,114,108,100]

### PR DESCRIPTION
**Pull request by bhalevy**
Currently, to_json of a std::string_view resolved to
the Range overload, and so it is printed as array of integers
rather than as a string.

For example: std::string_view("hello, world") is wrongly formatted
as [104,101,108,108,111,44,32,119,111,114,108,100]

Note that we add formatting both for std::string_view and for std::string.
The latter is required to resolve ambiguities with formatting of
seastar::sstring (when Seastar_SSTRING is ON).

Fixes #3183

### CODE REVIEW

**Comment by bhalevy** [comment]
[d344d5c](https://github.com/scylladb/seastar/commit/d344d5cb2706a573c0a748b97ed959787578086d): simplified, left only formatting for std::string_view since both std::string and seastar::sstring are implicitly convertible to std::string_view.
Doing so also saves consideration for Seastar_STRING build config option.

**Comment by bhalevy** [comment]
Hit https://github.com/scylladb/seastar/issues/3180

File: include/seastar/json/formatter.hh [hunk 1]
```diff
@@ -53,7 +53,7 @@ template<typename T>
 concept is_string_like =
     std::convertible_to<const T&, std::string_view> &&
     requires (T s) {
-        { s.data() } -> std::same_as<char*>;
+        { s.data() } -> std::convertible_to<const char*>;
         // sstring::length() and sstring::find() return size_t instead of
```
Comment (avikivity) [inline include/seastar/json/formatter.hh:57]: Perhaps a better approach is to replace is_string_like<T> with std::convertible_to<std::string_view, T>. Both sstring and std::string are convertible to std::string_view. is_string_like likely predates std::string_view.

But let's merge this first as the simplest fix.

**Comment by travisdowns** [comment]
Heads up: this is a breaking API change for downstream users. Types that have a user-defined conversion to `sstring` (but not to `std::string_view`) can no longer be passed to `formatter::to_json` / `formatter::write`.

Previously, `to_json(x)` worked when `x` had `operator sstring()` — one user-defined conversion bound it to `const sstring&`. After this change, the chain `x → sstring → string_view` requires two user-defined conversions, which C++ doesn't allow in implicit conversion sequences. Such types now fail to compile (and they don't satisfy the range overload either, unless they happen to expose `begin()/end()`).

Hit this in Redpanda where our `uuid_t` has `operator sstring() const` and was relied upon for JSON serialization. Might be worth keeping a `const sstring&` overload alongside the new `string_view` one to preserve the previous behavior.

**Comment by bhalevy** [comment]
> Heads up: this is a breaking API change for downstream users. Types that have a user-defined conversion to `sstring` (but not to `std::string_view`) can no longer be passed to `formatter::to_json` / `formatter::write`.
> 
> Previously, `to_json(x)` worked when `x` had `operator sstring()` — one user-defined conversion bound it to `const sstring&`. After this change, the chain `x → sstring → string_view` requires two user-defined conversions, which C++ doesn't allow in implicit conversion sequences. Such types now fail to compile (and they don't satisfy the range overload either, unless they happen to expose `begin()/end()`).
> 
> Hit this in Redpanda where our `uuid_t` has `operator sstring() const` and was relied upon for JSON serialization. Might be worth keeping a `const sstring&` overload alongside the new `string_view` one to preserve the previous behavior.

Can you please open a new issue about this with a concrete reproducer test?

**Comment by bhalevy** [comment]
> > Heads up: this is a breaking API change for downstream users. Types that have a user-defined conversion to `sstring` (but not to `std::string_view`) can no longer be passed to `formatter::to_json` / `formatter::write`.
> > Previously, `to_json(x)` worked when `x` had `operator sstring()` — one user-defined conversion bound it to `const sstring&`. After this change, the chain `x → sstring → string_view` requires two user-defined conversions, which C++ doesn't allow in implicit conversion sequences. Such types now fail to compile (and they don't satisfy the range overload either, unless they happen to expose `begin()/end()`).
> > Hit this in Redpanda where our `uuid_t` has `operator sstring() const` and was relied upon for JSON serialization. Might be worth keeping a `const sstring&` overload alongside the new `string_view` one to preserve the previous behavior.
> 
> Can you please open a new issue about this with a concrete reproducer test?

See https://github.com/scylladb/seastar/pull/3389

**Comment by avikivity** [comment]
> Heads up: this is a breaking API change for downstream users. Types that have a user-defined conversion to `sstring` (but not to `std::string_view`) can no longer be passed to `formatter::to_json` / `formatter::write`.
> 
> Previously, `to_json(x)` worked when `x` had `operator sstring()` — one user-defined conversion bound it to `const sstring&`. After this change, the chain `x → sstring → string_view` requires two user-defined conversions, which C++ doesn't allow in implicit conversion sequences. Such types now fail to compile (and they don't satisfy the range overload either, unless they happen to expose `begin()/end()`).
> 
> Hit this in Redpanda where our `uuid_t` has `operator sstring() const` and was relied upon for JSON serialization. Might be worth keeping a `const sstring&` overload alongside the new `string_view` one to preserve the previous behavior.

I don't think a C++ project can guarantee this level of source compatibility.

I try very hard to keep compatibility, but the maze of conversions can defeat any plan.

**Comment by travisdowns** [comment]
> Can you please open a new issue about this with a concrete reproducer test?

Based on your PR, I think you got it: it was an object with a conversion to `sstring` but not to `string_view` and double conversion is not allowed.

**Comment by travisdowns** [comment]
> I don't think a C++ project can guarantee this level of source compatibility.
> 
> I try very hard to keep compatibility, but the maze of conversions can defeat any plan.

yeah I this wasn't meant to be a major complaint or even a request to fix (already fixed on RP side), just a note and also a bit of assessment of how deep the source compatibility should go

**Comment by avikivity** [comment]
> > I don't think a C++ project can guarantee this level of source compatibility.
> > I try very hard to keep compatibility, but the maze of conversions can defeat any plan.
> 
> yeah I this wasn't meant to be a major complaint or even a request to fix (already fixed on RP side), just a note and also a bit of assessment of how deep the source compatibility should go

As deep as we can, but no deeper.
