### PR TITLE
Fix for missing cycles column and more

### LINKED ISSUE #2587: async PERF_TEST always returns 0 cycles
If you write a `PERF_TEST` (or any other variation like `PERF_TEST_F/C` etc) whose testing method is async, the "cycles" column is always zero.

### PR DESCRIPTION
**Pull request by travisdowns**
In this series:

 - perf_tests_perf: minimal self-benches for PERF_TEST stuff
 - De-duplicate perf_tests main loop, which also fixes #2587 

Example results for `perf_test_perf` after the fix:

```
test                             iterations      median         mad         min         max      allocs       tasks        inst      cycles
perf_tests.test_simple_1          774019546     1.313ns     0.019ns     1.259ns     1.333ns       0.000       0.000         7.0         5.0
perf_tests.test_simple_n         3188188100     0.330ns     0.001ns     0.308ns     0.387ns       0.000       0.000         3.1         1.3
perf_tests.test_ready_async_1    3638567766     0.280ns     0.005ns     0.271ns     0.290ns       0.000       0.000         4.0         1.1
perf_tests.test_ready_async_n    3179866200     0.312ns     0.006ns     0.305ns     0.435ns       0.000       0.000         3.1         1.3
perf_tests.test_unready_async_1    28622990    34.253ns     0.303ns    33.950ns    36.198ns       1.000       2.000       360.1       125.3
perf_tests.test_unready_async_n  1082973200     0.942ns     0.011ns     0.897ns     1.031ns       0.020       0.030         9.3         3.5
fixture.test_fixture_1            781121567     1.303ns     0.006ns     1.282ns     1.309ns       0.000       0.000         7.0         5.0
fixture.test_fixture_n           3096749700     0.330ns     0.005ns     0.318ns     0.363ns       0.000       0.000         3.1         1.3
fixture.test_coro_1                71657240    13.640ns     0.179ns    13.461ns    14.588ns       1.000       0.000       150.1        49.2
fixture.test_coro_n              2214644700     0.475ns     0.019ns     0.453ns     0.722ns       0.010       0.000         4.6         1.9
```

### CODE REVIEW

File: tests/perf/perf_tests_perf.cc [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+ * KIND, either express or implied.  See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+
+#include "seastar/core/future.hh"
+#include "seastar/coroutine/maybe_yield.hh"
+#include "seastar/util/later.hh"
+#include <seastar/core/coroutine.hh>
+#include <seastar/testing/perf_tests.hh>
```
Comment (avikivity) [inline tests/perf/perf_tests_perf.cc:23]: \<> includes please.

File: tests/perf/perf_tests_perf.cc [hunk 2]
```diff
@@ -0,0 +1,68 @@
+/*
+ * This file is open source software, licensed to you under the terms
+ * of the Apache License, Version 2.0 (the "License").  See the NOTICE file
+ * distributed with this work for additional information regarding copyright
```
Comment (avikivity) [inline tests/perf/perf_tests_perf.cc:4]: > These are benchmarks which just test minimal version of the various
> PERF_TEST flavors, with mostly empty test bodies. It is intended to
> test the overhead of the test framework, so that changes can be made
> without any large regressions. There are a lot of cases because
> internally the main perf test loop has different flavors depending
> on async or not, returning an iteration count or not, etc.

Please enrich the changelog with sample output.

File: tests/perf/perf_tests_perf.cc (hunk 1 above)
Comment (avikivity) [reply tests/perf/perf_tests_perf.cc:23]: @tchaikov could we enforce it? By using `-isystem include` instead of `-Iinclude`, though it would take me several weeks to figure out how to do it with cmake.

Comment (avikivity) [reply tests/perf/perf_tests_perf.cc:23]: Actually it wouldn't help.

Comment (travisdowns) [reply tests/perf/perf_tests_perf.cc:23]: sorry this is how clangd auto-adds headers, let me see if I can see how to do this right for the seastar way

**Comment by travisdowns** [comment]
Sample output of perf_tests_perf:
| test                            |  iterations |      median |         mad |         min |         max |      allocs |       tasks |        inst |
| -                               |           - |           - |           - |           - |           - |           - |           - |           - |
| perf_tests.test_simple_1        |   774019546 |     1.313ns |     0.019ns |     1.259ns |     1.333ns |       0.000 |       0.000 |         7.0 |
| perf_tests.test_simple_n        |  3188188100 |     0.330ns |     0.001ns |     0.308ns |     0.387ns |       0.000 |       0.000 |         3.1 |
| perf_tests.test_ready_async_1   |  3638567766 |     0.280ns |     0.005ns |     0.271ns |     0.290ns |       0.000 |       0.000 |         4.0 |
| perf_tests.test_ready_async_n   |  3179866200 |     0.312ns |     0.006ns |     0.305ns |     0.435ns |       0.000 |       0.000 |         3.1 |
| perf_tests.test_unready_async_1 |    28622990 |    34.253ns |     0.303ns |    33.950ns |    36.198ns |       1.000 |       2.000 |       360.1 |
| perf_tests.test_unready_async_n |  1082973200 |     0.942ns |     0.011ns |     0.897ns |     1.031ns |       0.020 |       0.030 |         9.3 |
| fixture.test_fixture_1          |   781121567 |     1.303ns |     0.006ns |     1.282ns |     1.309ns |       0.000 |       0.000 |         7.0 |
| fixture.test_fixture_n          |  3096749700 |     0.330ns |     0.005ns |     0.318ns |     0.363ns |       0.000 |       0.000 |         3.1 |
| fixture.test_coro_1             |    71657240 |    13.640ns |     0.179ns |    13.461ns |    14.588ns |       1.000 |       0.000 |       150.1 |
| fixture.test_coro_n             |  2214644700 |     0.475ns |     0.019ns |     0.453ns |     0.722ns |       0.010 |       0.000 |         4.6 |

File: tests/perf/perf_tests_perf.cc (hunk 2 above)
Comment (travisdowns) [reply tests/perf/perf_tests_perf.cc:4]: Good idea, sample out here (from after the coroutine change):

https://github.com/scylladb/seastar/pull/2588#issuecomment-2552232283

File: tests/perf/perf_tests_perf.cc (hunk 1 above)
Comment (travisdowns) [reply tests/perf/perf_tests_perf.cc:23]: fixed in push

**Comment by travisdowns** [comment]
Actually the output above shows the cycles column is missing from the `.md` output! Let me fix that.

Here's the non-md output corresponding to the above:

```
test                             iterations      median         mad         min         max      allocs       tasks        inst      cycles
perf_tests.test_simple_1          774019546     1.313ns     0.019ns     1.259ns     1.333ns       0.000       0.000         7.0         5.0
perf_tests.test_simple_n         3188188100     0.330ns     0.001ns     0.308ns     0.387ns       0.000       0.000         3.1         1.3
perf_tests.test_ready_async_1    3638567766     0.280ns     0.005ns     0.271ns     0.290ns       0.000       0.000         4.0         1.1
perf_tests.test_ready_async_n    3179866200     0.312ns     0.006ns     0.305ns     0.435ns       0.000       0.000         3.1         1.3
perf_tests.test_unready_async_1    28622990    34.253ns     0.303ns    33.950ns    36.198ns       1.000       2.000       360.1       125.3
perf_tests.test_unready_async_n  1082973200     0.942ns     0.011ns     0.897ns     1.031ns       0.020       0.030         9.3         3.5
fixture.test_fixture_1            781121567     1.303ns     0.006ns     1.282ns     1.309ns       0.000       0.000         7.0         5.0
fixture.test_fixture_n           3096749700     0.330ns     0.005ns     0.318ns     0.363ns       0.000       0.000         3.1         1.3
fixture.test_coro_1                71657240    13.640ns     0.179ns    13.461ns    14.588ns       1.000       0.000       150.1        49.2
fixture.test_coro_n              2214644700     0.475ns     0.019ns     0.453ns     0.722ns       0.010       0.000         4.6         1.9
```

**Comment by travisdowns** [comment]
The unrelated fix for the entirely missing cycles column (not simply zero) in perf tests is over there: https://github.com/scylladb/seastar/pull/2590

File: tests/perf/perf_tests_perf.cc (hunk 1 above)
Comment (tchaikov) [reply tests/perf/perf_tests_perf.cc:23]: > @tchaikov could we enforce it? By using `-isystem include` instead of `-Iinclude`, though it would take me several weeks to figure out how to do it with cmake.

created #2592

Comment (avikivity) [reply tests/perf/perf_tests_perf.cc:23]: Agree that not reporting errors would make it worse.

File: tests/perf/perf_tests_perf.cc (hunk 2 above)
Comment (avikivity) [reply tests/perf/perf_tests_perf.cc:4]: Looks like you forgot to add it to the cover letter.

Comment (travisdowns) [reply tests/perf/perf_tests_perf.cc:4]: It has been added it to the cover letter now.

File: tests/perf/perf_tests_perf.cc (hunk 1 above)
Comment (travisdowns) [reply tests/perf/perf_tests_perf.cc:23]: After poking the LLVM brear it looks like this _will_ be available in a future clangd version: https://github.com/llvm/llvm-project/pull/67749#issuecomment-2563964013

**Comment by travisdowns** [comment]
Not sure who is waiting for who here, but I believe I have addressed all feedback. Can you take a look @tchaikov ?

**Review by tchaikov — APPROVED** [review]
lgtm

**Comment by tchaikov** [comment]
> Not sure who is waiting for who here, but I believe I have addressed all feedback. Can you take a look @tchaikov ?

sure. but we still need the blessings from the seastar maintainers.

**Comment by tchaikov** [comment]
@scylladb/seastar-maint hello maintainers, could you help review this change?
