### PR TITLE
dns: serialize UDP sends.

### LINKED ISSUE #1285: DNS: simultaneous UDP queries can cause broken promises/fails/crash
Running N UDP queries at the same time (to same server) will cause multiple UDP packets being sent on the associated UDP channel, but we don't enforce the pending send has actually completed (as in been written to wire), and since seastar sockets cannot handle 
overlapping sends, this will break the mechanism. 

This is because C-ares does _not_ check for non-blocking EAGAIN state for UDP (long standing fixme in C-ares). 

Need to serialize UDP sends internally.

### PR DESCRIPTION
**Pull request by elcallio**
Fixes #1285
    
Running N UDP queries at the same time (to same server) will cause multiple UDP packets being sent on the
associated UDP channel, but we don't enforce the pending send has actually completed (as in been written to wire),
and since seastar sockets cannot handle overlapping sends, this will break the mechanism.

This is because C-ares does not check for non-blocking EAGAIN state for UDP (long standing fixme in C-ares).

Need to serialize UDP sends internally. 
Test included

v2: 
* Simplified solution to an always-future-chain for UDP.
* Added use/release for all send calls across either immediate or continuation to be extra paranoid of a dropped socket (from c-ares call).

### CODE REVIEW

File: src/net/dns.cc [hunk 1]
```diff
@@ -806,81 +806,106 @@ class net::dns_resolver::impl
...
+            break;
+        case type::udp:
+            // #1285 - serialize UDP sends if we are overlapping with a pending send.
+            if (!(e.avail & POLLOUT)) {
+                auto op = std::exchange(_send_waiters[fd], promise<>()); 
+                (void)_send_waiters[fd].get_future().then([me = shared_from_this(), op = std::move(op), fd, p = std::move(p), this]() mutable {
+                    op.set_value(); // make sure we signal chain.
+                    dns_log.trace("Send {} retry...", fd);
+                    send_packet(fd, std::move(p)); // try again.
+                });
```
Comment (avikivity) [inline src/net/dns.cc:857]: This is overkill, if _send_waiters[fd] is a future<> you can write

```c++
auto& chain = _send_waiters.at[fd];
chain = chain.then_wrapped(.... [] { return e.tcp.out->write(std::move(p)); });
```

btw I see no error handling on failed writes.

File: src/net/dns.cc [hunk 2]
```diff
@@ -806,81 +806,106 @@ class net::dns_resolver::impl
...
+           } catch (...) {
+           }
+           return -1;
+        }
+
+        // c-ares does _not_ use non-blocking retry for udp sockets. We just pretend
+        // all is fine even though we have no idea. Barring stack/adapter failure it
+        // is close to the same guarantee a "normal" message send would have anyway.
+        // For tcp we also pretend we're done, to make sure we don't have to deal with
+        // matching sent data
```
Comment (avikivity) [inline src/net/dns.cc:907]: When we tear down an fd, we need to wait for all sends to complete, otherwise we invite a use-after-free. If we convert promise to future, it's the usual combination of shutting down the fd + wait for the future chain to be ready.

Comment (elcallio) [reply src/net/dns.cc:907]: FD:s are used/released both in the actual send as well as calling gethostbyname etc. So it should be safe here. But I guess we could be even more defensive and do a use before any send + always release in either completion or immediately.

File: src/net/dns.cc (hunk 1 above)
Comment (avikivity) [reply src/net/dns.cc]: If there's an error we can mark the socket as broken and then return an error on the next send.

Though can a udp socket really get poisoned this way? Probably not (e.g. an error in a udp socket doesn't affect the next send, unlike tcp).

**Comment by elcallio** [comment]
Simplified solution. Now always chains.

**Comment by elcallio** [comment]
Note CI failed, but it looks like a docker problem...

File: tests/unit/dns_test.cc [hunk 3]
```diff
@@ -150,3 +151,33 @@ static future<> test_srv() {
...
+    auto d = ::make_lw_shared<dns_resolver>(std::move(opts));
+    return when_all(
+        d->resolve_name("www.google.com"),
+        d->resolve_name("www.google.com"),
+        d->resolve_name("www.google.com"),
+        d->resolve_name("www.google.com"),
+        d->resolve_name("www.google.com"),
+        d->resolve_name("www.google.com")
+    ).finally([d](auto&...) {}).discard_result();
+}
```
Comment (avikivity) [inline tests/unit/dns_test.cc:183]: Will the test fail before the fix? If so better reorder it (or squash into same commit), to avoid false positive during bisect.

File: src/net/dns.cc [hunk 4]
```diff
@@ -837,16 +839,34 @@ class net::dns_resolver::impl
...
+                    });
+                    // if we have a fast-fail, give error.
+                    if (e.udp.f.failed()) {
+                        try {
+                            e.udp.f.get();
+                        } catch (std::system_error& e) {
+                            errno = e.code().value();
+                        } catch (...) {
+                        }
+                        return -1;
```
Comment (avikivity) [inline src/net/dns.cc:857]: For cleanliness sake, reinitialize f here. I don't think it will break but futures are use-once things (future::get() with a T will move the T out).

File: src/net/dns.cc [hunk 5]
```diff
@@ -837,16 +839,34 @@ class net::dns_resolver::impl
                     f = e.tcp.out->write(std::move(p));
                     break;
                 case type::udp:
-                    f = e.udp.channel.send(e.udp.dst, std::move(p));
-                    break;
+                    // always chain UDP sends
+                    e.udp.f = e.udp.f.then([&e, p = std::move(p)]() mutable {
+                        auto f = e.udp.channel.send(e.udp.dst, std::move(p));;
```
[the remark this answers is not in the document]
Comment (elcallio) [reply src/net/dns.cc]: Ugh. But yes, consistent with the model of active pretend all is fine...

File: tests/unit/dns_test.cc (hunk 3 above)
Comment (elcallio) [reply tests/unit/dns_test.cc:183]: Done

File: src/net/dns.cc (hunk 4 above)
Comment (elcallio) [reply src/net/dns.cc:857]: Right

File: src/net/dns.cc (hunk 1 above)
Comment (elcallio) [reply src/net/dns.cc]: If the socket would be so broken, it will fast-fail me thinks. All else should/would be packet errors down the line...

**Comment by elcallio** [comment]
Updated

**Comment by elcallio** [comment]
ping?

**Comment by elcallio** [comment]
ping?
